FROM node:18-alpine
WORKDIR /core
ENV PATH="./node_modules/.bin:$PATH"
COPY . .
RUN yarn

ARG REACT_APP_WS_SERVER_URL
ARG REACT_APP_WS_SERVER_PORT
ENV REACT_APP_WS_SERVER_URL $REACT_APP_WS_SERVER_URL
ENV REACT_APP_WS_SERVER_PORT $REACT_APP_WS_SERVER_PORT

RUN yarn build
CMD ["yarn", "start"]
